name: Sincronizador Diario Diangel

on:
  schedule:
    # 07:00 UTC es exactamente las 02:00 a.m. en Colombia
    - cron: '0 7 * * *'
  workflow_dispatch: # Esto agrega un botón para que puedas correrlo manualmente cuando quieras

jobs:
  sincronizar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar herramientas del robot (Librerías)
        run: |
          python -m pip install --upgrade pip
          pip install pandas gspread selenium webdriver-manager google-api-python-client google-auth openpyxl

      - name: Reconstruir credenciales.json desde la bóveda secreta
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' > credenciales.json

      - name: ¡Ejecutar Sincronización!
        env:
          BELATRIZ_USER: ${{ secrets.BELATRIZ_USER }}
          BELATRIZ_PASS: ${{ secrets.BELATRIZ_PASS }}
        run: python sincronizador.py
